### PR TITLE
SECURITY: IMDSv2 support via new cluster_instance_metadata_options parameter

### PR DESCRIPTION
**Pull request by jeroenhabets**
Resolves main part of #79 a.o. IMDSv2 to prevent Server Side Request Forgery (SSRF) (OWASP Top-10)

Introduces new `cluster_instance_metadata_options` module parameter to control [launch_template.metadata-options](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#metadata-options) with secure default.
See also [Use IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) and [Add defense in depth against open firewalls, reverse proxies, and SSRF vulnerabilities with enhancements to the EC2 Instance Metadata Service](http://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/)

NOTE: In CHANGELOG.md warn users of this module of this change in the unlikely event they (still) can not utilize IMDSv2

### CODE REVIEW

**Comment by jeroenhabets** [comment]
@jonassvalin, @tobyclemson what can I do to speed up this PR?

**Comment by tobyclemson** [comment]
Hi @jeroenhabets,

Thanks for the contribution.

In terms of speeding things up, this PR doesn't include any tests for the newly added feature. If you could get those added (unit tests are sufficient) then that would help us get it merged quickly. Otherwise we'll need to add those ourselves and prioritise some time to do so. Note, you'll need to have some AWS credentials in your environment to run the unit tests since even though they test against a plan, they still require all prerequisite infrastructure to be deployed in order to run.

Additionally, the CHANGELOG should be updated with the specifics of the change, under an "Unreleased" section.

Let me know if you get stuck on any of this, or alternatively if you'd like us to prioritise some time to add the tests ourselves,
Thanks,
Toby

**Comment by jeroenhabets** [comment]
Hi @tobyclemson,

Due to how our AWS is structured, we are not able to accommodate (3rd party) unit tests any time soon, so even though I'd be happy to contribute some, I have currently no way to test them myself.

If you could help out here that would be appreciated.

P.S.  Are we the only security conscious user that is eager to embrace IMDSv2?

Thanks, Jeroen

**Comment by jeroenhabets** [comment]
@tobyclemson, @Gryff Thanks for all the good work 🥇 !

I would again plead against making `cluster_instance_metadata_options` not nullable, as this will force each user to have to think about this implementation detail. With sane defaults (at the moment IMDSv2 support enabled) they shouldn't have to and existing users are not forced to updated their configurations.

Of course, if you decide differently, I'll totally respect. Thanks again!

**Review by tobyclemson — APPROVED** [review]

**Comment by tobyclemson** [comment]
@jeroenhabets [6.1.0-rc.6](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.1.0-rc.6) has this change. Once I get your other PR merged, I'll prepare a release.

Thanks for hanging in there to get this merged.

**Pull request merged**
