### PR TITLE
Add a Capacity Provider and Container Insights

### PR DESCRIPTION
**Pull request by lparkes**
This PR adds a Capacity Provider resource to the ECS Cluster as well as turning on Container Insights by default.

### CODE REVIEW

**Comment by tobyclemson** [comment]
Hi! I'll take a look at this and try and get it merged over the weekend as it looks like it needs some tests. Thanks for the contribution!

**Comment by tobyclemson** [comment]
Hi all,

An update on this PR:
- I'm breaking out the container insights change as that seems independent and I can get that merged in immediately
- I'm also going to pull out the protect_from_scale_in change as that can also be merged independently
- On the wider capacity provider change, I need to make that backwards compatible / optional as I'm using this module with classic load balancers elsewhere and they don't support capacity providers. I also need to add tests.

I'll work on getting all this done today although the capacity provider change may take a bit longer. I'll update here as each piece is released.

Thanks!
Toby

**Comment by tobyclemson** [comment]
Release [3.2.0](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/3.2.0) includes an option to enable container insights.

Thanks,
Toby

**Comment by tobyclemson** [comment]
Release [3.3.0](https://github.com/Global-Online-Health/mypulse-mobile-apps) includes an option to protect ASG instances against scale in.

The variable is called `protect_cluster_instances_from_scale_in` accepting `yes` or `no` and defaulting to `no`.

Thanks,
Toby

**Comment by lparkes** [comment]
Thanks for doing this. I would have added some tests myself, but I got as far as seeing that Rake was being used and was all "yeah, nah".

**Comment by tobyclemson** [comment]
Capacity provider support is available in [3.4.0](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/3.4.0). 

To enable the capacity provider, pass `include_asg_capacity_provider = "yes"`. You can optionally disable managed termination protection and managed scaling using `asg_capacity_provider_manage_termination_protection = "yes"` and `asg_capacity_provider_manage_scaling = "yes"`. There are additional managed scaling parameters exposed as well.

Thanks,
Toby

**Pull request closed without merging**
