### PR TITLE
option to disable detailed monitoring, configure log retention

### PR DESCRIPTION
**Pull request by andrei-dascalu**
Disabled default detailed monitoring

-> https://github.com/infrablocks/terraform-aws-ecs-cluster/issues/33
-> https://github.com/infrablocks/terraform-aws-ecs-cluster/issues/74

Configure log retention days

### CODE REVIEW

**Comment by andrei-dascalu** [comment]
@tobyclemson I've updated the readme as well, but I'm not sure how to approach unit tests. They seem to be in Ruby(?) which isn't my forte, nor do I have the required tooling.

**Comment by tobyclemson** [comment]
Hi @andrei-dascalu 

Thanks for raising, we'll aim to take a look at adding tests this week.

Toby

**Comment by andrei-dascalu** [comment]
@tobyclemson that sounds great! I took the liberty of adding another option for the volume issue that should be backwards compatible.

**Comment by andrei-dascalu** [comment]
@tobyclemson no disrespect meant but is there a possibility this could get looked at this week or the next ? Thanks!

**Comment by tobyclemson** [comment]
@andrei-dascalu someone else from the team may be able to fit it in, I've been sidetracked with other things so haven't had a chance personally.

@Gryff @jonassvalin Do you think one of you would have time to take a look at the tests for this PR?

**Comment by jonassvalin** [comment]
@tobyclemson @andrei-dascalu Sure thing, I can pick it up.

**Comment by jonassvalin** [comment]
Hey @andrei-dascalu , I've added the necessary tests and merged the PR. There's an [RC 5.1.0-rc.1](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/5.1.0-rc.1) available now, if you can try it out and let me know if it works as you intended then I can go ahead and do a full release.

**Pull request merged**
