### PR TITLE
Make module `darwin_arm64` compatible

### LINKED ISSUE #30: Module not working on Mac with M1 (darwin_arm64)
# Problem
When I install this module (with `terraform init`) on my MacBook Pro with M1 processor, I get **`Incompatible provider version`**.

_See full error message_
image

# Analyze
The problem is, that this module use HasiCorp's deprecated [`Template Provider`](https://registry.terraform.io/providers/hashicorp/template/latest/docs). Because it's deprecated, HashiCorp don't provide a binary for `darin_arm64` (known as Apple's M1 processor).

# Solution
Use instead of `data "template_file` blocks Terraforms `locals` block with `templatefile` function.

### PR DESCRIPTION
**Pull request by fullheart**
Remove deprecated "Template Provider" Provider (see: https://registry.terraform.io/providers/hashicorp/template/latest/docs)
and use instead terraforms `locals` block and `templatefile` function.

resolve #30

### CODE REVIEW

**Comment by tobyclemson** [comment]
Thanks for this. I'll aim to review tomorrow.

It looks like there's a slight breaking change here since a provided `cluster_instance_user_data_template` will no longer have the `cluster_name` interpolated. However, I don't think there's any way around this so will likely make a major version release, along with a few other breaking changes I've been meaning to make for a while.

**Comment by tobyclemson** [comment]
@fullheart, sorry, I wasn't very clear.

In this: 

```
template_cluster_user_data = coalesce(var.cluster_instance_user_data_template, templatefile("${path.module}/user-data/cluster.tpl", {
    cluster_name = local.cluster_full_name
  }))
```

you are correct that the template at `"${path.module}/user-data/cluster.tpl"` will be interpolated with `cluster_name` as previously.

However, the way the module works currently is that you can pass `cluster_instance_user_data_template` as a string containing interpolation parameters, such as `$${cluster_name}`. The double `$$` is there to prevent the interpolation at the point that the string is created (i.e., by the module consumer), such that the string passed in is a template that can be interpolated similar to what sits in the file at `"${path.module}/user-data/cluster.tpl"`.

The `template` provider used to allow interpolation of strings as well as files, whereas `templatefile` only allows interpolation of files. As such, we've lost the ability to pass a `cluster_instance_user_data_template` variable with interpolation placeholders.

This is non-obvious behaviour so I'm looking to remove it from the module but it is a breaking change and will therefore need a little more thought.

**Comment by fullheart** [comment]
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog

**Comment by fullheart** [comment]
@tobyclemson  Sorry I click a wrong button (and have accidentally closed the PR). Now I reopen the PR again.

**Comment by fullheart** [comment]
@tobyclemson Thank you for your answer. Now I understand what you mean. Thank you for your time and effort to maintain this module.

**Comment by Gryff** [comment]
This was resolved in version `4.2.0`, closing.

**Pull request closed without merging**
