### PR TITLE
Ignore cluster_desired_capacity following autoscaling

### LINKED ISSUE #69: Ignoring changes to cluster_desired_capacity following autoscaling activities
Currently it seems to me that subsequent applies will always try to set the desired capacity to either what was provided during initial setup or the default '3' if the setting is removed.

This is really bad when the autoscaling group has changed the size between min and max but then the apply will try to take it back to whatever it was.

case in point, I have a cluster with min = 2, max = 12. It creates a cluster with 3 instances. Later on my workload leads to the cluster increasing to 6. Now whenever I apply I have to make sure to manually update the desired count to whatever it is at that time.

Suggestion:
no default desired value. If nothing is provided then the cluster should ignore lifecycle changes to the desired capacity (it will spin up base on min instance count anyway).

### PR DESCRIPTION
**Pull request by jeroenhabets**
Resolves #69 Drift in Autoscaling's desired_capacity will be ignored

### CODE REVIEW

**Comment by jonassvalin** [comment]
Hi @jeroenhabets , thanks for the contributions. 

I'll look to get to these by the end of this week.

Cheers

**Comment by jeroenhabets** [comment]
@jonassvalin, @tobyclemson what can I do to speed up this PR?

**Comment by tobyclemson** [comment]
Hi @jeroenhabets,

It looks like this one contains part of your other PR on adding volume tags. Would you be able to remove that in preference of the other PR?

With lifecycle changes, it's very difficult to test so we don't need any tests added in this case. However, if you have any ideas how we could test that, we'd welcome them :)

Thanks,
Toby

**Comment by jeroenhabets** [comment]
Hi @tobyclemson, 
OK, I reverted the last commit (it's been a while but I assume it was unintentional). No tests added indeed.
Regards, Jeroen

**Comment by tobyclemson** [comment]
@jeroenhabets, version [6.1.0-rc.2](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.1.0-rc.2) includes this change. 

I forgot to ask for the CHANGELOG to be updated for this one so I've also updated that - let me know if you think it needs further clarification.

Thanks,
Toby

**Comment by jeroenhabets** [comment]
@tobyclemson Thank you!

> The cluster_desired_capacity is now ignored after the first apply of the module since, in the case of autoscaling or manual scaling, the value may have changed between applys.

The why is less clear then in issue https://github.com/infrablocks/terraform-aws-ecs-cluster/issues/69 which is not referenced (!) but good enough for me.

If you do want to update the CHANGELOG.md I'd suggest something like:

The `cluster_desired_capacity` is now ignored after the first apply of the module to prevent scaling down of systems that have been scaled up, whether through autoscaling or manually, to handle more load (Resolves https://github.com/infrablocks/terraform-aws-ecs-cluster/issues/69)

**Pull request merged**
