### PR TITLE
Name and tag cluster worker EBS volumes

### PR DESCRIPTION
**Pull request by jeroenhabets**
Resolves 2nd part of #79 (missing volume tags)

### CODE REVIEW

**Comment by jeroenhabets** [comment]
@jonassvalin, @tobyclemson what can I do to speed up this PR?

**Comment by tobyclemson** [comment]
Hi @jeroenhabets,

Thanks for the contribution.

In terms of speeding things up, this PR doesn't include any tests for the newly added feature. If you could get those added (unit tests are sufficient) then that would help us get it merged quickly. Otherwise we'll need to add those ourselves and prioritise some time to do so. Note, you'll need to have some AWS credentials in your environment to run the unit tests since even though they test against a plan, they still require all prerequisite infrastructure to be deployed in order to run.

Additionally, the CHANGELOG should be updated with the specifics of the change, under an "Unreleased" section.

Let me know if you get stuck on any of this, or alternatively if you'd like us to prioritise some time to add the tests ourselves,
Thanks,
Toby

**Comment by tobyclemson** [comment]
@jeroenhabets, another idea, since you have been providing feedback / PRs on this module recently, I was wondering if you wanted to join our InfraBlocks support Slack channel. We have a number of InfraBlocks users there who often help each other with using / contributing to modules. It would give you a bit more of a direct line to the team.

If you're interested, send me your email address to toby@go-atomic.io and I'll get you invited.

**Comment by jeroenhabets** [comment]
@tobyclemson as requested I've added a line under "## Unreleased" of CHANGELOG.md

**Comment by tobyclemson** [comment]
@jeroenhabets [6.1.0-rc.6](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.1.0-rc.6) has this change. Once I get a couple of other things merged, I'll prepare a release.

Thanks for hanging in there to get this merged.

**Comment by tobyclemson** [comment]
@jeroenhabets [6.1.0-rc.7](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.1.0-rc.7) contains this change. Will perform a proper release soon.

Again, thanks for your patience.
Toby

**Pull request merged**
